### ISSUE TITLE
Feature request: means to redirect to a system protoc

### ISSUE THREAD

**Issue by SomeoneSerge** [sergeiivankov/protoc-prebuilt#2]
Hi! It'd be nice to have a way to make `init()` return a path to a user-managed installation of protoc. E.g. `protoc-prebuilt` could check if `PROTOC` is already set. Unless there's something that I missed, there's currently no way to achieve such behaviour

Thanks!

**Comment by sergeiivankov** [comment]
Hi, @SomeoneSerge! In this case you no need use `protoc-prebuilt` in general. If we don't do the work of downloading and installing protoc compiler, then everything that the library does it returning paths to protoc compiler and include directory. I mean that you don't need pull the dependencies if you expect that protoc already installed. You can check that environment variable `PROTOC` is exists in your biuld script. What you think about it?

If this functionality is still required, we need discuss how it should work. We pass protoc version to `init` function. Should library check system installed protoc version and compare it with passed in argument version or use system installed version anyway? Or accept in `init` argument `"system"` value, for example, and force use system installed protoc and return error if it not exists?

**Comment by SomeoneSerge** [comment]
> In this case you no need use protoc-prebuilt in general

Indeed, and I didn't quite explain myself clearly:)

My case is that of a [third party project](https://github.com/rerun-io/rerun/blob/a414f3f58cad2f681827b6cd7282752a39756766/examples/rust/objectron/Cargo.toml#L24) relying on `protoc-prebuilt`, because, I presume, it works for their platforms and makes life easier for them. I'd like to use that third party project in an environment, where binaries downloaded by `protoc-prebuilt` couldn't work (no `ld.so` in the "conventional" location). Proposing the third party that they use `protoc-prebuilt` conditionally (rather than `protoc-prebuilt` download conditionally) is an option. I imagine it's better to make `protoc-prebuilt` do a conditional download instead, because then we've addressed this case for all `protoc-prebuilt`'s users.

In addition, making the download conditional would be helpful for package distributions, which may be e.g. running their builds in sandboxes without access to the internet.

> Should library check system installed protoc version

I think this sounds like a desirable behaviour. In my case I'd be fine with `protoc-prebuilt` just assuming that it's the user's responsibility to ensure they choose a compatible protoc version. If `protoc-prebuilt` verifies the system binary's version, I maybe could see value in making the checks optional and controlled by an environment variable as well

**Comment by sergeiivankov** [comment]
Now I understand. Yes, we can add check local installation before download binaries. But question about protoc version is still opened.

If another library use `init` with specified version, it expects that `protoc-prebuilt` return path to binary passed version.

Yes, one of solutions - it use environment variable, but it complicates work with library.

Another solution - it check locally installed binary exists, check it version and if it's not compare with required version, try to download required. In whis way third party library get that it expect, 3rd level dependency user can run it in sandbox, but should provide required version binary exists there. This solution not break current API, so this update will be minore and doesn't require any changes in third party libraries.

**Comment by SomeoneSerge** [comment]
> If another library use init with specified version, it expects that protoc-prebuilt return path to binary passed version.

If a user tries to override `protoc-prebuilt`'s default behaviour using an environment variable, maybe they should just pay attention to what they're doing, and if they break something this way it's their fault, and not yours?

**Comment by SomeoneSerge** [comment]
If you'd really like to take extra care of the versions, here's a scheme I'd be most comfortable with:

1. If `PROTOC_PREBUILT_PATH=/a/b/c/d/bin/protoc` is set, proceed with this path. Otherwise download a binary
2. If using a prebuilt binary or the user sets e.g. `PROTOC_PREBUILT_NO_VERSION_CHECK`, skip the checks
3. If a check is required, obtain the binary's version, compare against the constraints, crash if the test fails

I'd prefer the deterministically failed build to an attempt at "fixing things", because if I asked to use a system-installed protoc and it's of the wrong version, then I almost certainly did so erroneously

But ofc that's just how I see it, you do what works best for you

**Comment by sergeiivankov** [comment]
Yes, I understand that it best solution for you. But I worried that described behavior can broke third party library and user may mistakenly think that problem in third party library, not in launched environment.

I think that compromise is force check locally installed protoc and require check passed version. If it not exists or versions not exual, try to download from github.

**Comment by sergeiivankov** [comment]
If you run your code in controlled by you environment, I think it not a problem install protoc version required by third party library.

**Comment by SomeoneSerge** [comment]
Sure, it's not a problem for me at all, I was just thinking that this would've been easier for you as well. And I don't see how you could break any third party libraries, since the user would have to explicitly set a protoc-prebuilt-specific environment variable to activate the new behaviour. They couldn't do that by accident, could they?

**Comment by sergeiivankov** [comment]
Sorry for very long feedback. Add required functional, see https://github.com/sergeiivankov/protoc-prebuilt/commit/fe88a63bf0efd95c4334945e2c15497050c5bfa7.
Thank you for taking part!

**Comment by sergeiivankov** [comment]
@SomeoneSerge, new version with this functional available https://crates.io/crates/protoc-prebuilt!

**Comment by SomeoneSerge** [comment]
Thanks a lot @sergeiivankov! I had worked around the problem that originally motivated me to open the issue, but I'm pretty sure I'll eventually need this feature again and will test the changes!
