### ISSUE TITLE
Add a feature to support obtaining proxy information from the system or through environment variables

### ISSUE THREAD

**Issue by soloist-v** [sergeiivankov/protoc-prebuilt#4]
Hi! Thank you for creating this crate. It is very useful to me, but since accessing GitHub in our country requires adding a proxy, I hope to add the proxy feature to crate.
```
[dependencies]
# rustem_proxy = "0.1.5"

[features]
proxy = []
```
```Rust
#[allow(clippy::result_large_err)]
fn get_with_token(url: &str, token: &Option<String>) -> Result<Response, ureq::Error> {
    let mut builder = ureq::builder();
    #[cfg(feature = "proxy")]
    {
        // let proxy = rustem_proxy::SystemProxy::get();
        // if proxy.is_enabled {
        //     let http_proxy = format!("http://{}:{}", proxy.host, proxy.port);
        //     let proxy = ureq::Proxy::new(http_proxy)?;
        //     builder = builder.proxy(proxy)
        // }
    }
    let mut req = builder.build().request("GET", url).set("User-Agent", CRATE_USER_AGENT);
    if let Some(value) = token {
        req = req.set("Authorization", &format!("Bearer {}", value))
    }
    req.call()
}
```
The implementation of rustem_proxy in Linux is currently incomplete.
https://github.com/uaquax/rustem_proxy/blob/3ddd0115750b2488a028db1a9670e3e36d4cc7c7/src/linux.rs#L13

**Comment by sergeiivankov** [comment]
Hi! It's good idea, thank you. I need that this create satisfied the maximum number of users, so here's my suggestion:
1) Add environment variable `PROTOC_PREBUILT_PROXY` to force use proxy.
2) Add library than can receive system proxy from settings and use it, this functional was hidden behind feature like `use-system-proxy`. If I correct understand, this case is most useful for you. But problem that I not found library which would be sufficiently functional. `rustem_proxy` - not support linux, `sysproxy` - not return protocol. Most suitable is `proxyconfig`, but it return list of proxy. Need to test all of them.
3) Add feature `use-env-proxy` to use proxy from environment variables, how does curl do it (https://everything.curl.dev/usingcurl/proxies/env).
4) Add feature `socks-proxy` to support it proxy type (`ureq` support it's behind feature).

**Comment by soloist-v** [comment]
You have been very thoughtful, I think Add feature use-env-proxy is a good way.

**Comment by sergeiivankov** [comment]
Hello. I came to conclusion that best and most convenient solution is using environment variables with curl agreement. This functional ready, see https://github.com/sergeiivankov/protoc-prebuilt/commit/5832dd181b0f4c58686a2eae3cc85584a9ef7ea8 and project readme.
Thank you!

**Comment by sergeiivankov** [comment]
@soloist-v, new version with this functional available https://crates.io/crates/protoc-prebuilt!
